sudo: false
language: python
python:
  - "3.5"
env:
  global:
    - RUNTEST_ARGS="-v --noinput"
  matrix:
    # Quality checks
    - TOXENV=flake8
    # Supported python/django versions
    - TOXENV=py27-django-18
    - TOXENV=py27-django-19
    - TOXENV=py27-django-110
    - TOXENV=py35-django-18
    - TOXENV=py35-django-19
    - TOXENV=py35-django-110
install:
  - pip install tox
script: tox
